service: serverless-go

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  timeout: 10
  memorySize: 512
  versionFunctions: false

  package:
    exclude:
      - ./**
    include:
      - ./bin/**

  environment:
    ${file(./configs/${self:provider.stage}.yml)}

custom:
  region: ${self:provider.region}
  stage:  ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  dynamo-books-name: ${self:custom.prefix}-books-catalog

functions:
  create:
    handler: bin/books/endpoints/create
    events:
      - http:
          path: books
          method: post

  read:
    handler: bin/books/endpoints/read
    events:
      - http:
          path: books
          method: get

  read_detail:
    handler: bin/books/endpoints/detail
    events:
      - http:
          path: books/{hashkey}
          method: get

  update:
    handler: bin/books/endpoints/update
    events:
      - http:
          path: books/hashkey
          method: put

  delete:
    handler: bin/books/endpoints/delete
    events:
      - http:
          path: books/{hashkey}
          method: delete


# CloudFormation template syntax
resources:
  Resources:
    #DynamoDB Books Table
    BooksCatalog:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamo-books-name}
        AttributeDefinitions:
          - AttributeName: hashkey
            AttributeType: S
        KeySchema:
          - AttributeName: hashkey
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 1
